name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ---------- UI/UX & Ikon ----------
  font_awesome_flutter: ^10.7.0
  getwidget: ^7.0.0 
  intl: ^0.18.1
  sizer: ^2.0.15 

  # ---------- BLOC/CUBIT ----------
  flutter_bloc: ^8.0.0 
  bloc: ^8.1.2 
  meta: ^1.11.0 
  equatable: ^2.0.5

  # ---------- Tambahan untuk web/network ----------
  shared_preferences: ^2.5.3 
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  device_info_plus: ^12.2.0
  webview_flutter: ^4.13.0
  dio: ^5.9.0
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
