name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ---------- BLOC/CUBIT ----------
  flutter_bloc: ^8.0.0 
  bloc: ^8.1.2 
  meta: ^1.11.0 
  
  # ---------- UI/UX & Formatting ----------
  getwidget: ^7.0.0 
  intl: ^0.18.1
  shared_preferences: ^2.5.3 
  sizer: ^2.0.15 

  # ---------- Tambahan untuk ikon/web/network ----------
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  device_info_plus: ^12.2.0
  webview_flutter: ^4.13.0
  dio: ^5.9.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Konfigurasi Aset
flutter:
  uses-material-design: true

  # Deklarasi folder untuk menyertakan semua aset (termasuk placeholder.png)
  assets:
    - assets/images/